# Generated by Django 5.0.1 on 2024-03-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_shippingadress_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
    ]
