# Generated by Django 5.0.1 on 2024-04-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_requires_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Temp', max_length=200),
        ),
    ]
