# Generated by Django 5.0.1 on 2024-04-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_shippingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionBG',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionEN',
            field=models.TextField(blank=True, null=True),
        ),
    ]
